# /docker-compose.yml
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=cupcake_user
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=meu_cupcake_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: